# TNO Terminology Design tools configuration file (yaml)

## General
scopedir: . # path of the scope directory where the SAF is located
onNotExist: warn # the action in case a `vsntag` was specified, but wasn't found in the SAF
output: . # (root) directory for output files to be written to

## Machine Readable Glossary Tool
mrgt:
  vsntag: # versiontag for which the MRG needs to be (re)generated. Leave empty to process all versions

## Human Readable Glossary Tool
hrgt:
  interpreter: basic
  converter: |+
    ### [{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}})\n
    {{#if glossaryText}}{{glossaryText}}{{else}}no `glossaryText` was specified for this entry.{{/if}}\n
  input:
    - "tev2-gloss*.md"

## Term Reference Resolution Tool
trrt:
  interpreter: basic # type of interpreter, either: a regex, "alt", or "basic"
  converter:
    >- # Type of converter, either: a mustache template, "http", or "markdown"
    <a
    href="{{localize navurl}}{{#if trait}}#{{trait}}{{/if}}"
    hovertext="{{#if hoverText}}{{hoverText}}{{else}}{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}: {{noRefs glossaryText type="markdown"}}{{/if}}"
    >{{showtext}}</a>
  force: true # toggle overwriting of existing files
  input: # glob pattern strings for files to be processed by the TRRT
    - "**/*.md"
